{% set version = "0.3.4" %}

package:
  name: glog
  version: {{ version }}

source:
  fn: glog-{{ version }}.tar.gz
  url: https://github.com/google/glog/archive/v{{ version }}.tar.gz
  sha256: ce99d58dce74458f7656a68935d7a0c048fa7b4626566a71b7f4e545920ceb10

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - autoconf
    - automake
    - libtool

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libglog.dylib)            # [osx]
    - exit $(test -f ${PREFIX}/lib/libglog_nothreads.dylib)  # [osx]
    - exit $(test -f ${PREFIX}/lib/libglog.so)               # [linux]
    - exit $(test -f ${PREFIX}/lib/libglog_nothreads.so)     # [linux]

about:
  home: https://github.com/google/glog
  license: BSD 3-Clause
  license_file: COPYING
  summary: C++ implementation of the Google logging module.

extra:
  recipe-maintainers:
    - jakirkham
