travis:
  secure:
    BINSTAR_TOKEN: KQd83mdPkq/6KOAohHpl7q/TfobpoSR7tGq2KW6qc59gjfSoQTQjneZA5Ej32lOs9gajNzK/CoRJK8+Q07ql2LkjbkUBhzbVZgL57pzxeCPV6xLpgprOGdZlq3tZyE7zb5uv2RL0Ujt0rcqIvItiEXP5ztRr9RBhtynavE84JAEYUPbm6jD4HijFErqrSdAPWu23SkQ73crRP60wgL2wsatz8fmGdyCxJEx2aFPb6dsGgVlEsHzAh5WcMtUy07U0Tqn9eTZ46lUEeQSgn/MZ9+4u0eereezhDU3umyoNXw74szlaiNowDqGp7pmRlaEaXOeE9ry8qZbtfUF6zzyR/YDorrXKrlRtBrwB4XDPl4yrbqUO9ZIgr4zQ0NxtYxMlDAISKwCsbgU+r0eg7dHK4/ONDtbg1iWTNypQ5IUkJUGoTokiAocbkTgKiS/YdFYyI1j5EDs7U6ALYYU9O0QAjVxIH1eK2nZ3Ydd4uw2DAA+aGUjXu9AiaInDo4wTdSuiK/cbAJLVmCvZRvDDuEHzYK1Cq90PuThAxgzCdCNA5HMAGp8mIGOLsDWn1ybQ5HMF4AGXhoF/Nl7OzeDmIVmh/pQPskH7VLJoQMaM/Ys/ihEmpFB+97Ro8vlWMKjBFanfvGCp24K8bDJPGfyjeavkqnlJ1yV7Q7pC0eqKdwx9O8Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
