travis:
  secure:
    BINSTAR_TOKEN: WUygNeNZzXi+WLwFzJsqwcKUbMYyeBhT+fIgGJD3VWXaTjRvAtTA8n9A2pY/pZo3BO1G9WpyDCG+0KcrAKujHk0njMh3mhb/W3pWDPkGgqUbqzhobzg+OUAqX0gDu7CvUZA9oyjZKzst5ZpDTk8G8jAz3jhaCFqb9LcKtIgyFM7u5xY+iq09pLTVOOdsqmNjusFdON65D5SlmbxCpbwVAB6NwiOzYmG+BQ3/0rsUiIG8AXXYOz2mueCchdJUf4jCqkGONvipBrHR3Yj0y1UAdsfbfjVd5CWYwbDxvT/0PwxoswfKr9ORbe/tEGThbIOiW0bgio5cP0kIGpvqQDqCTJmDf786VRsvJcjHfV3k9yB4dZjCuI+qL237EYOG2xyFAeCyoJ7F78mWctpUC6B67yybV5nFOxQ8EO+MYM102OmjrDKoIKs3kw5exdFzq8GCmytcJ5IchHbQgrf5iLbn+3Bmr0OlL4YB/bsDQVkBlCN1tYdbboXILe7eGU+TqYTpH4OussBXj3sRM/rxoBjuEgih6RtpKNxMm7WPpr8H2laYUnABf7UW7Cgtr8TZFXt905Zc6gdnRpwbuA5cfw6THqwAU5bOF/Hhx6ufj0Q4uI+jd5HaX+0xfFADsTcKRE7GiBBy86BpkO7WaHSQL70FcoA7onvouaf4QazFKHQXOl4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
